// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using StoreDataLayer.Data;
using System;

namespace StoreDataLayer.Migrations
{

    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StoreDataLayer.Models.Order", b =>
                {
                    b.Property<string>("TrackingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tracking_id");

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .HasColumnName("address_name");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnName("city");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnName("state");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnName("street_address");

                    b.Property<int>("UserID")
                        .HasColumnName("user_id");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnName("zip_code");

                    b.HasKey("TrackingId");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("StoreDataLayer.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnName("last_name");

                    b.Property<int>("OrderId")
                        .HasColumnName("order_id");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StoreDataLayer.Models.Order", b =>
                {
                    b.HasOne("StoreDataLayer.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
